---
- hosts: master
  remote_user: cluster
  become: yes

  tasks:
  - name: install mpi
    apt: name=mpich state=latest

- hosts: nodes
  remote_user: cluster
  become: yes

  tasks:
  - name: install mpi on older ubuntu
    apt: name=mpich2 state=latest
    when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '14.04'

  - name: install mpi on newer ubuntu
    apt: name=mpich state=latest
    when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '16.04'

- hosts: master nodes
  remote_user: cluster
  become: yes

  tasks:
  - name: config hostnames
    lineinfile:
      dest: /etc/hosts
      line: '192.168.2.10 master'

  - lineinfile:
      dest: /etc/hosts
      line: '192.168.2.11 node1'

  - lineinfile:
      dest: /etc/hosts
      line: '192.168.2.12 node2'

  - lineinfile:
      dest: /etc/hosts
      line: '192.168.2.13 node3'

